### ISSUE TITLE
The new "deepspeed" requires env PATH CUDA_HOME

### ISSUE THREAD

**Issue by MackNcD** [daswer123/xtts-webui#10]
My python may be acting funny, but after trouble-shooting, I came up the error that the deepspeed 'wheel' wasn't acting correctly, and in the error info it said there was no path to CUDA_HOME (as an environment variable)

Do you have that on your system? If so, you should put this link in your README. 

https://developer.nvidia.com/cuda-downloads?target_os=Windows&target_arch=x86_64&target_version=11&target_type=exe_local

If you didn't have to install that, and add it to your ENV PATHs, then it may be a different issue altogether. Note: I haven't yet tried for this solution, I wanted to see if you knew anything about it first, considering there's nothing directly concerning it  on the README.

EDIT:
I looked into your changes, noticed that you changed the 11.8 torch to the newer version -- which my GPU isn't compatible with, with its current drivers (and I've been told to be careful upgrading GPU drivers if you use SD because the newer ones may really slow down inferencing, due to some offloading to RAM issue)
Does this deepspeed require 12.1? Or can I get away with possibly deleting it and throwing 11.8 in there instead?

Or is the initial root of the issue what I, initially thought it was? Thanks a million, loving the improvements.

**Comment by daswer123** [comment]
I changed and then returned, now I need cuda 11.8 , I'm not going to go higher because of the dependence of some libraries

**Comment by MackNcD** [comment]
Did you just change back recently, I believe I may have the 12.1...
Also, is there a CUDA_HOME already in your paths?
If you didn't have to download it, I'm curious about whether or not it's necessary and perhaps I can find out the core issue and post it whenever I do.

**Comment by MackNcD** [comment]
**ALERT! DO NOT ADD THE LINK TO THE README!**

Okay, for anyone searching issues that was having with the normal ```pip install -r requirements.txt```
When you're install your dependencies, **DO NOT simply pip install deepspeed like any other module.**

_Just run_
````python scripts/modeldownloader.py```

Make sure python is in your PATH -- check with ```python --version``` in whatever cmd prompt you do your python stuff in.
IF NOTHING COMES UP, LINK YOUR PATH DIRECTLY TO YOUR PYTHON.EXE, NOT THE SCRIPTS DIRECTORY. NORMALLY YOU WON'T HAVE TO DO THIS, BUT IF SUCH A THING OCCURS, THIS IS A WAY TO GET AROUND IT.

**Comment by daswer123** [comment]
I'll add that to the instructions for manual installation, thanks for checking everything out

**Comment by MackNcD** [comment]
No problem! 
One last thing. For anyone launching from a code editor, remember to remove the commented out 'launch demo' line, and 'untab it' -- bring to far left side. For those unfamiliar with python, but happen to be running an editor, this will help, just a bit, lol.

**Comment by daswer123** [comment]
> One last thing. For anyone launching from a code editor, remember to remove the commented out 'launch demo' line, it should be at the very bottom of the xtts_webui.py

Removed the comment so others wouldn't have to do it

**Comment by daswer123** [comment]
About CUDA, yes I have both 11.8 and 12.1 in the paths, I change them when I need it.

xtts_webui.py can work with CUDA 12.1 , but xtts_finetune_webui can't do it, it needs CUDA 11.8 because of the faster-whisper library, that's why I have CUDA 11.8 in the project requirements.

There are prebuild wheels for CUDA 12.1 for windows, you can find them here 
https://github.com/erew123/alltalk_tts/releases/tag/deepspeed

**Comment by MackNcD** [comment]
Spasibo!

Now that the new build is launching, I hate to come to you with more issues -- I'll work on them but you know your own UI better than I do, so maybe you'll spot the line more quickly... This is with the 'improve output quality/reduce noise' optoin checked:

> Traceback (most recent call last):
  File "C:\Users\user\xtts-webui-main\.venv\lib\site-packages\gradio\queueing.py", line 459, in call_prediction   
    output = await route_utils.call_process_api(
  File "C:\Users\user\xtts-webui-main\.venv\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\user\xtts-webui-main\.venv\lib\site-packages\gradio\blocks.py", line 1533, in process_api        
    result = await self.call_function(
  File "C:\Users\user\xtts-webui-main\.venv\lib\site-packages\gradio\blocks.py", line 1151, in call_function      
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\user\xtts-webui-main\.venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\user\xtts-webui-main\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\user\xtts-webui-main\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run      
    result = context.run(func, *args)
  File "C:\Users\user\xtts-webui-main\.venv\lib\site-packages\gradio\utils.py", line 678, in wrapper
    response = f(*args, **kwargs)
  File "c:\Users\user\xtts-webui-main\xtts_webui.py", line 295, in generate_audio
    output_file = improve_and_convert_audio(output_file,output_type)
  File "c:\Users\user\xtts-webui-main\scripts\funcs.py", line 159, in improve_and_convert_audio
    ffmpeg
  File "C:\Users\user\xtts-webui-main\.venv\lib\site-packages\ffmpeg\_run.py", line 284, in run_async
    return subprocess.Popen(
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1456, in _execute_child    
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\user\xtts-webui-main\.venv\lib\site-packages\gradio\queueing.py", line 459, in call_prediction   
    output = await route_utils.call_process_api(
  File "C:\Users\user\xtts-webui-main\.venv\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\user\xtts-webui-main\.venv\lib\site-packages\gradio\blocks.py", line 1533, in process_api        
    result = await self.call_function(
  File "C:\Users\user\xtts-webui-main\.venv\lib\site-packages\gradio\blocks.py", line 1151, in call_function      
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\user\xtts-webui-main\.venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\user\xtts-webui-main\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\user\xtts-webui-main\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run      
    result = context.run(func, *args)
  File "C:\Users\user\xtts-webui-main\.venv\lib\site-packages\gradio\utils.py", line 678, in wrapper
    response = f(*args, **kwargs)
  File "c:\Users\user\xtts-webui-main\xtts_webui.py", line 295, in generate_audio
    output_file = improve_and_convert_audio(output_file,output_type)
  File "c:\Users\user\xtts-webui-main\scripts\funcs.py", line 159, in improve_and_convert_audio
    ffmpeg
  File "C:\Users\user\xtts-webui-main\.venv\lib\site-packages\ffmpeg\_run.py", line 284, in run_async
    return subprocess.Popen(
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1456, in _execute_child    
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\xtts-webui-main\.venv\lib\site-packages\gradio\queueing.py", line 497, in process_events    
    response = await self.call_prediction(awake_events, batch)
  File "C:\Users\user\xtts-webui-main\.venv\lib\site-packages\gradio\queueing.py", line 468, in call_prediction   
    raise Exception(str(error) if show_error else None) from error
Exception: None
2023-12-21 22:38:26.268 | INFO     | scripts.tts_funcs:local_generation:236 - Processing time: 15.75 seconds.
2023-12-21 22:39:13.120 | INFO     | scripts.tts_funcs:local_generation:236 - Processing time: 15.05 seconds.
2023-12-21 22:40:08.728 | INFO     | scripts.tts_funcs:local_generation:236 - Processing time: 14.05 seconds.
Traceback (most recent call last):
  File "C:\Users\user\xtts-webui-main\.venv\lib\site-packages\gradio\queueing.py", line 459, in call_prediction   
    output = await route_utils.call_process_api(
  File "C:\Users\user\xtts-webui-main\.venv\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\user\xtts-webui-main\.venv\lib\site-packages\gradio\blocks.py", line 1533, in process_api        
    result = await self.call_function(
  File "C:\Users\user\xtts-webui-main\.venv\lib\site-packages\gradio\blocks.py", line 1151, in call_function      
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\user\xtts-webui-main\.venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\user\xtts-webui-main\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\user\xtts-webui-main\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run      
    result = context.run(func, *args)
  File "C:\Users\user\xtts-webui-main\.venv\lib\site-packages\gradio\utils.py", line 678, in wrapper
    response = f(*args, **kwargs)
  File "c:\Users\user\xtts-webui-main\xtts_webui.py", line 295, in generate_audio
    output_file = improve_and_convert_audio(output_file,output_type)
  File "c:\Users\user\xtts-webui-main\scripts\funcs.py", line 159, in improve_and_convert_audio
    ffmpeg
  File "C:\Users\user\xtts-webui-main\.venv\lib\site-packages\ffmpeg\_run.py", line 284, in run_async
    return subprocess.Popen(
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1456, in _execute_child    
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\user\xtts-webui-main\.venv\lib\site-packages\gradio\queueing.py", line 459, in call_prediction   
    output = await route_utils.call_process_api(
  File "C:\Users\user\xtts-webui-main\.venv\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\user\xtts-webui-main\.venv\lib\site-packages\gradio\blocks.py", line 1533, in process_api        
    result = await self.call_function(
  File "C:\Users\user\xtts-webui-main\.venv\lib\site-packages\gradio\blocks.py", line 1151, in call_function      
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\user\xtts-webui-main\.venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\user\xtts-webui-main\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\user\xtts-webui-main\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run      
    result = context.run(func, *args)
  File "C:\Users\user\xtts-webui-main\.venv\lib\site-packages\gradio\utils.py", line 678, in wrapper
    response = f(*args, **kwargs)
  File "c:\Users\user\xtts-webui-main\xtts_webui.py", line 295, in generate_audio
    output_file = improve_and_convert_audio(output_file,output_type)
  File "c:\Users\user\xtts-webui-main\scripts\funcs.py", line 159, in improve_and_convert_audio
    ffmpeg
  File "C:\Users\user\xtts-webui-main\.venv\lib\site-packages\ffmpeg\_run.py", line 284, in run_async
    return subprocess.Popen(
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1456, in _execute_child    
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\xtts-webui-main\.venv\lib\site-packages\gradio\queueing.py", line 497, in process_events    
    response = await self.call_prediction(awake_events, batch)
  File "C:\Users\user\xtts-webui-main\.venv\lib\site-packages\gradio\queueing.py", line 468, in call_prediction   
    raise Exception(str(error) if show_error else None) from error
    
 The normal inferencing worked just fine, going through all other options now to make sure everything is good -- looks like you spotted the UI type-o I was going to mention as well.

**Comment by MackNcD** [comment]
Very good news and slightly bad news:
As per my uses the new functionallity works fine: The outputs have indeed been added to the output folder, and with much quicker speed, and with higher quality.

The only bad news is that they are not registered by the WebUI display. This realization occured prior to FFMPEG so it had nothing to do with that. I can live with that the ultra high quality versions being displayed in WebUI as I specifically use the files regardless.

Both resemblance and the noise reduction function work like a charm -- aside from webUI direct preview.

Great work so far man, this is really well done.

**Comment by daswer123** [comment]
Thank you. I'm glad my work is useful.

> The only bad news is that they are not registered by the WebUI display. This realization occured prior to FFMPEG so it had nothing to do with that. I can live without the ultra high quality versions being displayed in WebUI as I specifically use the files regardless.

I plan to add a status field to display progress status and error messages
