### ISSUE TITLE
RVC Error

### ISSUE THREAD

**Issue by GalenMarek14** [daswer123/xtts-webui#16]
The main app works as intended but RVC postprocessing gives this error:
```
2023-12-26 16:20:11.406 | INFO     | scripts.tts_funcs:local_generation:306 - Processing time: 44.92 seconds.
['scripts/rvc/test_infer.py', '0', 'output/output_(1)_11Labs - MALE - Matthew - British, Calm, Audiobook.wav', 'D:\\XTTSAdvancedWEBUI\\LATESTwithRVC\\xtts-webui\\rvc\\11Labs - MALE - Matthew - British, Calm, Audiobook\\added_IVF173_Flat_nprobe_1_11Labs - MALE - Matthew - British, Calm, Audiobook_v2.index', 'rmvpe', 'D:\\XTTSAdvancedWEBUI\\LATESTwithRVC\\xtts-webui\\output\\11Labs - MALE - Matthew - British, Calm, Audiobook_11Labs - MALE - Matthew - British, Calm, Audiobook_1.wav', 'D:\\XTTSAdvancedWEBUI\\LATESTwithRVC\\xtts-webui\\rvc\\11Labs - MALE - Matthew - British, Calm, Audiobook\\11Labs - MALE - Matthew - British, Calm, Audiobook.pth', '0.8', 'cuda:0', 'true', '3', '0', '1', '0.33', '128', '50', '1100', 'false']
Traceback (most recent call last):
  File "D:\XTTSAdvancedWEBUI\LATESTwithRVC\xtts-webui\scripts\rvc\test_infer.py", line 119, in <module>
    from infer_pack.models import (
  File "D:\XTTSAdvancedWEBUI\LATESTwithRVC\xtts-webui\scripts\rvc\infer_pack\models.py", line 6, in <module>
    from lib.infer_pack import modules
ModuleNotFoundError: No module named 'lib.infer_pack'
Traceback (most recent call last):
  File "D:\XTTSAdvancedWEBUI\LATESTwithRVC\venv\lib\site-packages\gradio\queueing.py", line 459, in call_prediction
    output = await route_utils.call_process_api(
  File "D:\XTTSAdvancedWEBUI\LATESTwithRVC\venv\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\XTTSAdvancedWEBUI\LATESTwithRVC\venv\lib\site-packages\gradio\blocks.py", line 1542, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\XTTSAdvancedWEBUI\LATESTwithRVC\venv\lib\site-packages\gradio\blocks.py", line 1428, in postprocess_data
    outputs_cached = processing_utils.move_files_to_cache(
  File "D:\XTTSAdvancedWEBUI\LATESTwithRVC\venv\lib\site-packages\gradio\processing_utils.py", line 265, in move_files_to_cache
    return client_utils.traverse(data, _move_to_cache, client_utils.is_file_obj)
  File "D:\XTTSAdvancedWEBUI\LATESTwithRVC\venv\lib\site-packages\gradio_client\utils.py", line 917, in traverse
    return func(json_obj)
  File "D:\XTTSAdvancedWEBUI\LATESTwithRVC\venv\lib\site-packages\gradio\processing_utils.py", line 257, in _move_to_cache
    temp_file_path = move_resource_to_block_cache(payload.path, block)
  File "D:\XTTSAdvancedWEBUI\LATESTwithRVC\venv\lib\site-packages\gradio\processing_utils.py", line 234, in move_resource_to_block_cache
    return block.move_resource_to_block_cache(url_or_file_path)
  File "D:\XTTSAdvancedWEBUI\LATESTwithRVC\venv\lib\site-packages\gradio\blocks.py", line 257, in move_resource_to_block_cache
    temp_file_path = processing_utils.save_file_to_cache(
  File "D:\XTTSAdvancedWEBUI\LATESTwithRVC\venv\lib\site-packages\gradio\processing_utils.py", line 170, in save_file_to_cache
    temp_dir = hash_file(file_path)
  File "D:\XTTSAdvancedWEBUI\LATESTwithRVC\venv\lib\site-packages\gradio\processing_utils.py", line 102, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\XTTSAdvancedWEBUI\\LATESTwithRVC\\xtts-webui\\output\\11Labs - MALE - Matthew - British, Calm, Audiobook_11Labs - MALE - Matthew - British, Calm, Audiobook_1.wav'
Traceback (most recent call last):
  File "D:\XTTSAdvancedWEBUI\LATESTwithRVC\venv\lib\site-packages\gradio\queueing.py", line 459, in call_prediction
    output = await route_utils.call_process_api(
  File "D:\XTTSAdvancedWEBUI\LATESTwithRVC\venv\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\XTTSAdvancedWEBUI\LATESTwithRVC\venv\lib\site-packages\gradio\blocks.py", line 1542, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\XTTSAdvancedWEBUI\LATESTwithRVC\venv\lib\site-packages\gradio\blocks.py", line 1428, in postprocess_data
    outputs_cached = processing_utils.move_files_to_cache(
  File "D:\XTTSAdvancedWEBUI\LATESTwithRVC\venv\lib\site-packages\gradio\processing_utils.py", line 265, in move_files_to_cache
    return client_utils.traverse(data, _move_to_cache, client_utils.is_file_obj)
  File "D:\XTTSAdvancedWEBUI\LATESTwithRVC\venv\lib\site-packages\gradio_client\utils.py", line 917, in traverse
    return func(json_obj)
  File "D:\XTTSAdvancedWEBUI\LATESTwithRVC\venv\lib\site-packages\gradio\processing_utils.py", line 257, in _move_to_cache
    temp_file_path = move_resource_to_block_cache(payload.path, block)
  File "D:\XTTSAdvancedWEBUI\LATESTwithRVC\venv\lib\site-packages\gradio\processing_utils.py", line 234, in move_resource_to_block_cache
    return block.move_resource_to_block_cache(url_or_file_path)
  File "D:\XTTSAdvancedWEBUI\LATESTwithRVC\venv\lib\site-packages\gradio\blocks.py", line 257, in move_resource_to_block_cache
    temp_file_path = processing_utils.save_file_to_cache(
  File "D:\XTTSAdvancedWEBUI\LATESTwithRVC\venv\lib\site-packages\gradio\processing_utils.py", line 170, in save_file_to_cache
    temp_dir = hash_file(file_path)
  File "D:\XTTSAdvancedWEBUI\LATESTwithRVC\venv\lib\site-packages\gradio\processing_utils.py", line 102, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\XTTSAdvancedWEBUI\\LATESTwithRVC\\xtts-webui\\output\\11Labs - MALE - Matthew - British, Calm, Audiobook_11Labs - MALE - Matthew - British, Calm, Audiobook_1.wav'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\XTTSAdvancedWEBUI\LATESTwithRVC\venv\lib\site-packages\gradio\queueing.py", line 497, in process_events
    response = await self.call_prediction(awake_events, batch)
  File "D:\XTTSAdvancedWEBUI\LATESTwithRVC\venv\lib\site-packages\gradio\queueing.py", line 468, in call_prediction
    raise Exception(str(error) if show_error else None) from error
Exception: None
```
My RVC folder:
![image](https://github.com/daswer123/xtts-webui/assets/148660654/38c05544-9947-478b-9d3c-6b12043b8f83)
![image](https://github.com/daswer123/xtts-webui/assets/148660654/94ce358f-838c-4672-9865-1f0b87c539a6)
![image](https://github.com/daswer123/xtts-webui/assets/148660654/78ee1d9e-229a-42ba-a7ed-70ae4f228dc6)

**Comment by daswer123** [comment]
Hi, thanks for letting me know, I'll try to figure out what's wrong.

**Comment by daswer123** [comment]
Sort of fixed it, checked on a friend's computer, everything works.

**Comment by GalenMarek14** [comment]
Thank you! It works now :)
