### ISSUE TITLE
Error when using rvc

### ISSUE THREAD

**Issue by Wuzzooy** [daswer123/xtts-webui#19]
Hello,

I have an error when trying to use rvc

"FileNotFoundError: [Errno 2] No such file or directory: 'H:\\xtts-webui-main\\output\\female_Scarlett_1.wav'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "H:\xtts-webui-main\venv\Lib\site-packages\gradio\queueing.py", line 497, in process_events
    response = await self.call_prediction(awake_events, batch)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\xtts-webui-main\venv\Lib\site-packages\gradio\queueing.py", line 468, in call_prediction
    raise Exception(str(error) if show_error else None) from error
Exception: None"
The file name output i've got in the ouput folder when trying to generate was "output_(1)_female.wav" using the reference speaker "female"

![rvc](https://github.com/daswer123/xtts-webui/assets/147096942/517d3c3b-e398-4400-bb15-09ca072dca11)

**Comment by daswer123** [comment]
Hi sorry I didn't reply earlier, it should be working now, I guess :)

**Comment by Wuzzooy** [comment]
Hello,
No problem for the late reply, I'm really grateful for your work.
I still had this issue when trying to use rvc and found out that there is an issue with fairsec and python 3.11 so i used a fix from an issue opened about it.
for windows i used in the rvc_venv
pip install git+https://github.com/liyaodev/fairseq.git

https://github.com/facebookresearch/fairseq/issues/5012#issuecomment-1884159687

It's working now.
I had another small issue, i had a message saying "no supported nvidia gpu found".
I installed pytorch in the rvc_venv and it worked aswell.

**Comment by daswer123** [comment]
Thanks for checking and looking into the situation. Your answer will help.

**Comment by hrachkovinovoto** [comment]
> Thanks for checking and looking into the situation. Your answer will help.

Hello, have you found a full solution to the issue yet? I was also getting the same error and although the temporary fix above gets it to work again, I don't really use it anymore and the reason for that is because it's just extremely slow. It takes nearly a minute to generate through RVC here on a 3 second long sample whereas that very same sample over at the updated Mangio-RVC completes in less than 2 seconds. I noticed that it keeps on reloading the rmvpe model during each time I tried to generate, maybe that's partially why it takes forever? With that aside, everything else is working perfectly! 

<img width="668" alt="image" src="https://github.com/daswer123/xtts-webui/assets/101092444/9ae1ce5a-0506-46b9-9576-273f4526ffbb">

**Comment by llpcasey** [comment]
> > Thanks for checking and looking into the situation. Your answer will help.
> 
> Hello, have you found a full solution to the issue yet? I was also getting the same error and although the temporary fix above gets it to work again, I don't really use it anymore and the reason for that is because it's just extremely slow. It takes nearly a minute to generate through RVC here on a 3 second long sample whereas that very same sample over at the updated Mangio-RVC completes in less than 2 seconds. I noticed that it keeps on reloading the rmvpe model during each time I tried to generate, maybe that's partially why it takes forever? With that aside, everything else is working perfectly!
> <img alt="image" width="668" src="https://private-user-images.githubusercontent.com/101092444/303683140-9ae1ce5a-0506-46b9-9576-273f4526ffbb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NjU1NjUsIm5iZiI6MTcwOTY2NTI2NSwicGF0aCI6Ii8xMDEwOTI0NDQvMzAzNjgzMTQwLTlhZTFjZTVhLTA1MDYtNDZiOS05NTc2LTI3M2Y0NTI2ZmZiYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQxOTAxMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYjBkZTg3Mjc2ZGVkMTMxZTM0YjI3NTQ5ZjlkYjliNTY5YzczYWI3MTEzYWY3MjgxMzRhZjgxZjhhODA1MzgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4QcAUPwWDxNzM_OcfnPJeAuelkmGiH2NGmuD8Nv6wJc">

Hello, did you find solution for this?
