### ISSUE TITLE
Japanese doesn't work

### ISSUE THREAD

**Issue by Chris2918** [daswer123/xtts-webui#2]
When trying to generate something in Japanese, I get this error
At first it said something about cutlet being missing, so I pip installed cutlet and then this error appeared
This is the error

Traceback (most recent call last):
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\gradio\queueing.py", line 459, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\gradio\blocks.py", line 1533, in process_api
    result = await self.call_function(
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\gradio\blocks.py", line 1151, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\gradio\utils.py", line 678, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\lccji\Downloads\xtts-webui-main\xtts_webui.py", line 194, in generate_audio
    output_file = XTTS.process_tts_to_file(text, lang_code, ref_speaker_wav, options, output_file_path)
  File "C:\Users\lccji\Downloads\xtts-webui-main\scripts\tts_funcs.py", line 293, in process_tts_to_file
    raise e  # Propagate exceptions for endpoint handling.
  File "C:\Users\lccji\Downloads\xtts-webui-main\scripts\tts_funcs.py", line 287, in process_tts_to_file
    self.api_generation(clear_text,speaker_wav,language,options,output_file)
  File "C:\Users\lccji\Downloads\xtts-webui-main\scripts\tts_funcs.py", line 239, in api_generation
    self.model.tts_to_file(
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\TTS\api.py", line 334, in tts_to_file
    wav = self.tts(
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\TTS\api.py", line 276, in tts
    wav = self.synthesizer.tts(
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\TTS\utils\synthesizer.py", line 386, in tts
    outputs = self.tts_model.synthesize(
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\TTS\tts\models\xtts.py", line 419, in synthesize
    return self.full_inference(text, speaker_wav, language, **settings)
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\TTS\tts\models\xtts.py", line 488, in full_inference
    return self.inference(
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\TTS\tts\models\xtts.py", line 534, in inference
    text_tokens = torch.IntTensor(self.tokenizer.encode(sent, lang=language)).unsqueeze(0).to(self.device)
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\TTS\tts\layers\xtts\tokenizer.py", line 649, in encode
    txt = self.preprocess_text(txt, lang)
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\TTS\tts\layers\xtts\tokenizer.py", line 638, in preprocess_text
    txt = japanese_cleaners(txt, self.katsu)
  File "C:\Users\lccji\AppData\Local\Programs\Python\Python310\lib\functools.py", line 981, in __get__
    val = self.func(instance)
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\TTS\tts\layers\xtts\tokenizer.py", line 620, in katsu
    return cutlet.Cutlet()
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\cutlet\cutlet.py", line 148, in __init__
    self.tagger = fugashi.Tagger(mecab_args)
  File "fugashi\fugashi.pyx", line 383, in fugashi.fugashi.Tagger.__init__
  File "fugashi\fugashi.pyx", line 232, in fugashi.fugashi.GenericTagger.__init__
RuntimeError:
Failed initializing MeCab. Please see the README for possible solutions:

    https://github.com/polm/fugashi

If you are still having trouble, please file an issue here, and include the
ERROR DETAILS below:

    https://github.com/polm/fugashi/issues

issueを英語で書く必要はありません。

------------------- ERROR DETAILS ------------------------
arguments: [b'fugashi', b'-C']
param.cpp(69) [ifs] no such file or directory: c:\mecab\mecabrc
----------------------------------------------------------

Traceback (most recent call last):
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\gradio\queueing.py", line 459, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\gradio\blocks.py", line 1533, in process_api
    result = await self.call_function(
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\gradio\blocks.py", line 1151, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\gradio\utils.py", line 678, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\lccji\Downloads\xtts-webui-main\xtts_webui.py", line 194, in generate_audio
    output_file = XTTS.process_tts_to_file(text, lang_code, ref_speaker_wav, options, output_file_path)
  File "C:\Users\lccji\Downloads\xtts-webui-main\scripts\tts_funcs.py", line 293, in process_tts_to_file
    raise e  # Propagate exceptions for endpoint handling.
  File "C:\Users\lccji\Downloads\xtts-webui-main\scripts\tts_funcs.py", line 287, in process_tts_to_file
    self.api_generation(clear_text,speaker_wav,language,options,output_file)
  File "C:\Users\lccji\Downloads\xtts-webui-main\scripts\tts_funcs.py", line 239, in api_generation
    self.model.tts_to_file(
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\TTS\api.py", line 334, in tts_to_file
    wav = self.tts(
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\TTS\api.py", line 276, in tts
    wav = self.synthesizer.tts(
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\TTS\utils\synthesizer.py", line 386, in tts
    outputs = self.tts_model.synthesize(
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\TTS\tts\models\xtts.py", line 419, in synthesize
    return self.full_inference(text, speaker_wav, language, **settings)
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\TTS\tts\models\xtts.py", line 488, in full_inference
    return self.inference(
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\TTS\tts\models\xtts.py", line 534, in inference
    text_tokens = torch.IntTensor(self.tokenizer.encode(sent, lang=language)).unsqueeze(0).to(self.device)
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\TTS\tts\layers\xtts\tokenizer.py", line 649, in encode
    txt = self.preprocess_text(txt, lang)
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\TTS\tts\layers\xtts\tokenizer.py", line 638, in preprocess_text
    txt = japanese_cleaners(txt, self.katsu)
  File "C:\Users\lccji\AppData\Local\Programs\Python\Python310\lib\functools.py", line 981, in __get__
    val = self.func(instance)
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\TTS\tts\layers\xtts\tokenizer.py", line 620, in katsu
    return cutlet.Cutlet()
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\cutlet\cutlet.py", line 148, in __init__
    self.tagger = fugashi.Tagger(mecab_args)
  File "fugashi\fugashi.pyx", line 383, in fugashi.fugashi.Tagger.__init__
  File "fugashi\fugashi.pyx", line 232, in fugashi.fugashi.GenericTagger.__init__
RuntimeError:
Failed initializing MeCab. Please see the README for possible solutions:

    https://github.com/polm/fugashi

If you are still having trouble, please file an issue here, and include the
ERROR DETAILS below:

    https://github.com/polm/fugashi/issues

issueを英語で書く必要はありません。

------------------- ERROR DETAILS ------------------------
arguments: [b'fugashi', b'-C']
param.cpp(69) [ifs] no such file or directory: c:\mecab\mecabrc
----------------------------------------------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\gradio\queueing.py", line 497, in process_events
    response = await self.call_prediction(awake_events, batch)
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\gradio\queueing.py", line 468, in call_prediction
    raise Exception(str(error) if show_error else None) from error
Exception: None

**Comment by daswer123** [comment]
Hi thanks for letting me know, updated the dependencies, now you need to reinstall and everything should work

**Comment by Chris2918** [comment]
Thank you! It works now
