### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/app/xtts_api_server/models/v2.0.2/config.json'

### ISSUE THREAD

**Issue by gab-luz** [daswer123/xtts-webui#21]
So, I'm basically trying to deploy xtts but I get the error below:
FileNotFoundError: [Errno 2] No such file or directory: '/app/xtts_api_server/models/v2.0.2/config.json'

Here's my full log:
docker compose up
```
[+] Running 0/1
 ⠿ xttsapiserver Error                                                                                                                                                                   2.4s
[+] Building 751.2s (13/13) FINISHED                                                                                                                                                          
 => [internal] load build definition from Dockerfile                                                                                                                                     0.3s
 => => transferring dockerfile: 1.16kB                                                                                                                                                   0.1s
 => [internal] load .dockerignore                                                                                                                                                        0.3s
 => => transferring context: 2B                                                                                                                                                          0.1s
 => [internal] load metadata for docker.io/nvidia/cuda:12.1.0-runtime-ubuntu22.04                                                                                                        1.8s
 => [stage-0 1/8] FROM docker.io/nvidia/cuda:12.1.0-runtime-ubuntu22.04@sha256:402700b179eb764da6d60d99fe106aa16c36874f7d7fb3e122251ff6aea8b2f7                                          0.0s
 => [internal] load build context                                                                                                                                                        0.5s
 => => transferring context: 5.67MB                                                                                                                                                      0.4s
 => CACHED [stage-0 2/8] RUN --mount=type=cache,target=/var/cache/apt,sharing=locked,rw apt-get update &&     apt-get install --no-install-recommends -y python3-dev portaudio19-dev li  0.0s
 => CACHED [stage-0 3/8] RUN --mount=type=cache,target=/root/.cache/pip,rw pip3 install virtualenv                                                                                       0.0s
 => CACHED [stage-0 4/8] RUN --mount=type=cache,target=/root/.cache/pip,rw     pip3 install --upgrade pip setuptools wheel ninja &&     pip3 install torch torchvision torchaudio xform  0.0s
 => CACHED [stage-0 5/8] RUN mkdir /app                                                                                                                                                  0.0s
 => CACHED [stage-0 6/8] WORKDIR /app                                                                                                                                                    0.0s
 => [stage-0 7/8] ADD . /app                                                                                                                                                             0.8s
 => [stage-0 8/8] RUN --mount=type=cache,target=/root/.cache/pip,rw     pip3 install /app                                                                                              741.0s
 => exporting to image                                                                                                                                                                   6.7s
 => => exporting layers                                                                                                                                                                  6.7s
 => => writing image sha256:572578d8657a5e9f6eb1232f92dd7ebbf34f3a585cddc6db08cc6f0b909f6147                                                                                             0.0s 
 => => naming to docker.io/library/xttsapiserver                                                                                                                                         0.0s 
[+] Running 2/2                                                                                                                                                                               
 ⠿ Network docker_default            Created                                                                                                                                             0.2s 
 ⠿ Container docker-xttsapiserver-1  Created                                                                                                                                             0.9s
Attaching to docker-xttsapiserver-1
docker-xttsapiserver-1  | 
docker-xttsapiserver-1  | ==========
docker-xttsapiserver-1  | == CUDA ==
docker-xttsapiserver-1  | ==========
docker-xttsapiserver-1  | 
docker-xttsapiserver-1  | CUDA Version 12.1.0
docker-xttsapiserver-1  | 
docker-xttsapiserver-1  | Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
docker-xttsapiserver-1  | 
docker-xttsapiserver-1  | This container image and its contents are governed by the NVIDIA Deep Learning Container License.
docker-xttsapiserver-1  | By pulling and using the container, you accept the terms and conditions of this license:
docker-xttsapiserver-1  | https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license
docker-xttsapiserver-1  | 
docker-xttsapiserver-1  | A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.
docker-xttsapiserver-1  | 
docker-xttsapiserver-1  | *************************
docker-xttsapiserver-1  | ** DEPRECATION NOTICE! **
docker-xttsapiserver-1  | *************************
docker-xttsapiserver-1  | THIS IMAGE IS DEPRECATED and is scheduled for DELETION.
docker-xttsapiserver-1  |     https://gitlab.com/nvidia/container-images/cuda/blob/master/doc/support-policy.md
docker-xttsapiserver-1  | 
docker-xttsapiserver-1  | 2024-01-01 18:31:15.026 | INFO     | xtts_api_server.tts_funcs:create_directories:221 - Folder in the path /app/output has been created
docker-xttsapiserver-1  | 2024-01-01 18:31:15.026 | INFO     | xtts_api_server.tts_funcs:create_directories:221 - Folder in the path /app/models has been created
docker-xttsapiserver-1  | 2024-01-01 18:31:15.028 | INFO     | xtts_api_server.server:<module>:76 - Model: 'v2.0.2' starts to load,wait until it loads
docker-xttsapiserver-1  | [XTTS] Downloading config.json...
100%|██████████| 4.36k/4.36k [00:00<00:00, 4.71MiB/s]
docker-xttsapiserver-1  | [XTTS] Downloading model.pth...
100%|██████████| 1.86G/1.86G [16:11<00:00, 1.92MiB/s]   
docker-xttsapiserver-1  | [XTTS] Downloading vocab.json...
100%|██████████| 335k/335k [00:00<00:00, 1.43MiB/s]
docker-xttsapiserver-1  | Traceback (most recent call last):
docker-xttsapiserver-1  |   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
docker-xttsapiserver-1  |     return _run_code(code, main_globals, None,
docker-xttsapiserver-1  |   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
docker-xttsapiserver-1  |     exec(code, run_globals)
docker-xttsapiserver-1  |   File "/app/xtts_api_server/__main__.py", line 46, in <module>
docker-xttsapiserver-1  |     from xtts_api_server.server import app
docker-xttsapiserver-1  |   File "/app/xtts_api_server/server.py", line 77, in <module>
docker-xttsapiserver-1  |     XTTS.load_model()
docker-xttsapiserver-1  |   File "/app/xtts_api_server/tts_funcs.py", line 146, in load_model
docker-xttsapiserver-1  |     self.model = TTS(model_path=checkpoint_dir,config_path=config_path).to(self.device)
docker-xttsapiserver-1  |   File "/usr/local/lib/python3.10/dist-packages/TTS/api.py", line 70, in __init__
docker-xttsapiserver-1  |     self.config = load_config(config_path) if config_path else None
docker-xttsapiserver-1  |   File "/usr/local/lib/python3.10/dist-packages/TTS/config/__init__.py", line 91, in load_config
docker-xttsapiserver-1  |     with fsspec.open(config_path, "r", encoding="utf-8") as f:
docker-xttsapiserver-1  |   File "/usr/local/lib/python3.10/dist-packages/fsspec/core.py", line 103, in __enter__
docker-xttsapiserver-1  |     f = self.fs.open(self.path, mode=mode)
docker-xttsapiserver-1  |   File "/usr/local/lib/python3.10/dist-packages/fsspec/spec.py", line 1295, in open
docker-xttsapiserver-1  |     f = self._open(
docker-xttsapiserver-1  |   File "/usr/local/lib/python3.10/dist-packages/fsspec/implementations/local.py", line 180, in _open
docker-xttsapiserver-1  |     return LocalFileOpener(path, mode, fs=self, **kwargs)
docker-xttsapiserver-1  |   File "/usr/local/lib/python3.10/dist-packages/fsspec/implementations/local.py", line 302, in __init__
docker-xttsapiserver-1  |     self._open()
docker-xttsapiserver-1  |   File "/usr/local/lib/python3.10/dist-packages/fsspec/implementations/local.py", line 307, in _open
docker-xttsapiserver-1  |     self.f = open(self.path, mode=self.mode)
docker-xttsapiserver-1  | FileNotFoundError: [Errno 2] No such file or directory: '/app/xtts_api_server/models/v2.0.2/config.json'
docker-xttsapiserver-1 exited with code 1
```

**Comment by daswer123** [comment]
Hi, I know about the docker bug, I am planning to fix this problem soon

**Comment by illtellyoulater** [comment]
wait so the api work already?
