### ISSUE TITLE
Deepspeed RuntimeError: Workspace can't be allocated, no enough memory. - Win 11

### ISSUE THREAD

**Issue by GalenMarek14** [daswer123/xtts-webui#25]
This project works on my Win 10 computer but gives this error on my friend's Win 11. Using this without --deepspeed option fixes the issue and it generates text successfully but it's much slower without deepspeed. How can we fix this?

![image](https://github.com/daswer123/xtts-webui/assets/148660654/72248dc9-cf88-4be2-adfa-d3134d7e8b85)
![image](https://github.com/daswer123/xtts-webui/assets/148660654/5d2c13a1-4317-4932-a014-562d353a205f)

```
To create a public link, set `share=True` in `launch()`.
Using ready reference
Requested:      104873984
Free:   49217536
Total:  4294443008
Traceback (most recent call last):
  File "C:\Users\furka\AI\xtts\venv\lib\site-packages\gradio\queueing.py", line 489, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\Users\furka\AI\xtts\venv\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\furka\AI\xtts\venv\lib\site-packages\gradio\blocks.py", line 1561, in process_api
    result = await self.call_function(
  File "C:\Users\furka\AI\xtts\venv\lib\site-packages\gradio\blocks.py", line 1179, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\furka\AI\xtts\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\furka\AI\xtts\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "C:\Users\furka\AI\xtts\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "C:\Users\furka\AI\xtts\venv\lib\site-packages\gradio\utils.py", line 678, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\furka\AI\xtts\xtts-webui\modules\generation.py", line 169, in generate_audio
    output_file = XTTS.process_tts_to_file(text, lang_code, ref_speaker_wav, options, output_file_path)
  File "C:\Users\furka\AI\xtts\xtts-webui\scripts\tts_funcs.py", line 378, in process_tts_to_file
    raise e  # Propagate exceptions for endpoint handling.
  File "C:\Users\furka\AI\xtts\xtts-webui\scripts\tts_funcs.py", line 370, in process_tts_to_file
    self.local_generation(clear_text,ref_speaker_wav,speaker_wav,language,options,output_file)
  File "C:\Users\furka\AI\xtts\xtts-webui\scripts\tts_funcs.py", line 287, in local_generation
    out = self.model.inference(
  File "C:\Users\furka\AI\xtts\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\furka\AI\xtts\venv\lib\site-packages\TTS\tts\models\xtts.py", line 541, in inference
    gpt_codes = self.gpt.generate(
  File "C:\Users\furka\AI\xtts\venv\lib\site-packages\TTS\tts\layers\xtts\gpt.py", line 590, in generate
    gen = self.gpt_inference.generate(
  File "C:\Users\furka\AI\xtts\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\furka\AI\xtts\venv\lib\site-packages\transformers\generation\utils.py", line 1764, in generate
    return self.sample(
  File "C:\Users\furka\AI\xtts\venv\lib\site-packages\transformers\generation\utils.py", line 2861, in sample
    outputs = self(
  File "C:\Users\furka\AI\xtts\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\furka\AI\xtts\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\furka\AI\xtts\venv\lib\site-packages\TTS\tts\layers\xtts\gpt_inference.py", line 97, in forward
    transformer_outputs = self.transformer(
  File "C:\Users\furka\AI\xtts\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\furka\AI\xtts\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\furka\AI\xtts\venv\lib\site-packages\transformers\models\gpt2\modeling_gpt2.py", line 888, in forward
    outputs = block(
  File "C:\Users\furka\AI\xtts\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\furka\AI\xtts\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\furka\AI\xtts\venv\lib\site-packages\deepspeed\model_implementations\transformers\ds_transformer.py", line 141, in forward
    self.allocate_workspace(self.config.hidden_size, self.config.heads,
RuntimeError: Workspace can't be allocated, no enough memory.
```

**Comment by daswer123** [comment]
Hi, well, the error speaks for itself. Try closing unnecessary programs before launching
