### ISSUE TITLE
Fine tuning broken on latest update

### ISSUE THREAD

**Issue by GamingDaveUk** [daswer123/xtts-webui#28]
Just did a git pull to make sure its all up to date and then tried to fine tune a model (havent fully figured out how to use them(only load them) but getting them trained ready)
However clicking step one results in this error:
```
H:\XTTS\xtts-webui\venv\lib\site-packages\gradio\utils.py:848: UserWarning: Expected maximum 5 arguments for function <function preprocess_dataset at 0x000002E2843D4310>, received 6.
  warnings.warn(
Running on local URL:  http://localhost:8011

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "H:\XTTS\xtts-webui\venv\lib\site-packages\gradio\queueing.py", line 459, in call_prediction
    output = await route_utils.call_process_api(
  File "H:\XTTS\xtts-webui\venv\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "H:\XTTS\xtts-webui\venv\lib\site-packages\gradio\blocks.py", line 1533, in process_api
    result = await self.call_function(
  File "H:\XTTS\xtts-webui\venv\lib\site-packages\gradio\blocks.py", line 1151, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "H:\XTTS\xtts-webui\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "H:\XTTS\xtts-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "H:\XTTS\xtts-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "H:\XTTS\xtts-webui\venv\lib\site-packages\gradio\utils.py", line 678, in wrapper
    response = f(*args, **kwargs)
  File "H:\XTTS\xtts-webui\venv\lib\site-packages\gradio\utils.py", line 678, in wrapper
    response = f(*args, **kwargs)
TypeError: preprocess_dataset() takes from 4 to 5 positional arguments but 7 were given
Traceback (most recent call last):
  File "H:\XTTS\xtts-webui\venv\lib\site-packages\gradio\queueing.py", line 459, in call_prediction
    output = await route_utils.call_process_api(
  File "H:\XTTS\xtts-webui\venv\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "H:\XTTS\xtts-webui\venv\lib\site-packages\gradio\blocks.py", line 1533, in process_api
    result = await self.call_function(
  File "H:\XTTS\xtts-webui\venv\lib\site-packages\gradio\blocks.py", line 1151, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "H:\XTTS\xtts-webui\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "H:\XTTS\xtts-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "H:\XTTS\xtts-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "H:\XTTS\xtts-webui\venv\lib\site-packages\gradio\utils.py", line 678, in wrapper
    response = f(*args, **kwargs)
  File "H:\XTTS\xtts-webui\venv\lib\site-packages\gradio\utils.py", line 678, in wrapper
    response = f(*args, **kwargs)
TypeError: preprocess_dataset() takes from 4 to 5 positional arguments but 7 were given

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "H:\XTTS\xtts-webui\venv\lib\site-packages\gradio\queueing.py", line 497, in process_events
    response = await self.call_prediction(awake_events, batch)
  File "H:\XTTS\xtts-webui\venv\lib\site-packages\gradio\queueing.py", line 468, in call_prediction
    raise Exception(str(error) if show_error else None) from error
Exception: None
```

**Comment by GamingDaveUk** [comment]
> Hi, I decided to remove this interface as I implemented a faster version in xtts-webui
> 
> ![Gradio](https://private-user-images.githubusercontent.com/22278673/295652133-065c68c1-7aed-41b4-9bb3-0b1383df25aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5MjY4MzgsIm5iZiI6MTcwNDkyNjUzOCwicGF0aCI6Ii8yMjI3ODY3My8yOTU2NTIxMzMtMDY1YzY4YzEtN2FlZC00MWI0LTliYjMtMGIxMzgzZGYyNWFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDIyNDIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3MzhmMzllMjYzN2M1ODI3Mzk1YmFjZDI3MTU5MGZjMGY5MDhmMjkxNGE0YzRmY2MyMDIxMDdmOTc2ZjcxN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lOGNndZwQkEaaB9NUrsKj1i51PAUNNWRZWipASTCI-k)

Much neater to have it all in one interface.

I am still confused as to how we use these models in the api and the webui though? 

I was able to load the model both in the webui and the api. However the webui still requires me to select a speaker wav file and this becomes the voice, not the fine tuned model. 

With the API I cant see how to send a json packet to it that doesnt use wav file and thus the same issue as above.

How do i tell the webui and the api that I do not want to use the selected wav file but instead wish to use the finetuned model?
