### ISSUE TITLE
Can't start webui

### ISSUE THREAD

**Issue by Boof2015** [daswer123/xtts-webui#3]
As the title says, I cannot start the webui. Honestly not sure where to go from here. Here is the error:

```
'deepspeed' already installed.
2023-12-16 01:22:36.921 | INFO     | xtts_webui:<module>:64 - Start loading model v2.0.2
G:\More_AI\XTTS COMBO\xtts-webui\venv\lib\site-packages\pydantic\_internal\_config.py:321: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
* 'validate_all' has been renamed to 'validate_default'
  warnings.warn(message, UserWarning)
G:\More_AI\XTTS COMBO\xtts-webui\venv\lib\site-packages\pydantic\_internal\_fields.py:149: UserWarning: Field "model_persistence_threshold" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
G:\More_AI\XTTS COMBO\xtts-webui\venv\lib\site-packages\pydantic\_internal\_config.py:321: UserWarning: Valid config keys have changed in V2:
* 'validate_all' has been renamed to 'validate_default'
  warnings.warn(message, UserWarning)
Traceback (most recent call last):
  File "G:\More_AI\XTTS COMBO\xtts-webui\app.py", line 28, in <module>
    from xtts_webui import demo
  File "G:\More_AI\XTTS COMBO\xtts-webui\xtts_webui.py", line 66, in <module>
    XTTS.load_model(this_dir)
  File "G:\More_AI\XTTS COMBO\xtts-webui\scripts\tts_funcs.py", line 86, in load_model
    self.load_local_model(this_dir)
  File "G:\More_AI\XTTS COMBO\xtts-webui\scripts\tts_funcs.py", line 106, in load_local_model
    self.model.load_checkpoint(config,use_deepspeed=USE_DEEPSPEED, checkpoint_dir=str(checkpoint_dir))
  File "G:\More_AI\XTTS COMBO\xtts-webui\venv\lib\site-packages\TTS\tts\models\xtts.py", line 783, in load_checkpoint
    self.gpt.init_gpt_for_inference(kv_cache=self.args.kv_cache, use_deepspeed=use_deepspeed)
  File "G:\More_AI\XTTS COMBO\xtts-webui\venv\lib\site-packages\TTS\tts\layers\xtts\gpt.py", line 222, in init_gpt_for_inference
    import deepspeed
  File "G:\More_AI\XTTS COMBO\xtts-webui\venv\lib\site-packages\deepspeed\__init__.py", line 15, in <module>
    from . import module_inject
  File "G:\More_AI\XTTS COMBO\xtts-webui\venv\lib\site-packages\deepspeed\module_inject\__init__.py", line 3, in <module>
    from .replace_module import replace_transformer_layer, revert_transformer_layer, ReplaceWithTensorSlicing, GroupQuantizer, generic_injection
  File "G:\More_AI\XTTS COMBO\xtts-webui\venv\lib\site-packages\deepspeed\module_inject\replace_module.py", line 803, in <module>
    from ..pipe import PipelineModule
  File "G:\More_AI\XTTS COMBO\xtts-webui\venv\lib\site-packages\deepspeed\pipe\__init__.py", line 3, in <module>
    from ..runtime.pipe import PipelineModule, LayerSpec, TiedLayerSpec
  File "G:\More_AI\XTTS COMBO\xtts-webui\venv\lib\site-packages\deepspeed\runtime\pipe\__init__.py", line 3, in <module>
    from .module import PipelineModule, LayerSpec, TiedLayerSpec
  File "G:\More_AI\XTTS COMBO\xtts-webui\venv\lib\site-packages\deepspeed\runtime\pipe\module.py", line 16, in <module>
    from ..activation_checkpointing import checkpointing
  File "G:\More_AI\XTTS COMBO\xtts-webui\venv\lib\site-packages\deepspeed\runtime\activation_checkpointing\checkpointing.py", line 25, in <module>
    from deepspeed.runtime.config import DeepSpeedConfig
  File "G:\More_AI\XTTS COMBO\xtts-webui\venv\lib\site-packages\deepspeed\runtime\config.py", line 30, in <module>
    from ..monitor.config import get_monitor_config
  File "G:\More_AI\XTTS COMBO\xtts-webui\venv\lib\site-packages\deepspeed\monitor\config.py", line 70, in <module>
    class DeepSpeedMonitorConfig(DeepSpeedConfigModel):
  File "G:\More_AI\XTTS COMBO\xtts-webui\venv\lib\site-packages\deepspeed\monitor\config.py", line 82, in DeepSpeedMonitorConfig
    def check_enabled(cls, values):
  File "G:\More_AI\XTTS COMBO\xtts-webui\venv\lib\site-packages\pydantic\deprecated\class_validators.py", line 231, in root_validator
    return root_validator()(*__args)  # type: ignore
  File "G:\More_AI\XTTS COMBO\xtts-webui\venv\lib\site-packages\pydantic\deprecated\class_validators.py", line 237, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

For further information visit https://errors.pydantic.dev/2.5/u/root-validator-pre-skip
Press any key to continue . . .
```

**Comment by daswer123** [comment]
Hi thanks for letting me know, can you edit the `start_xtts_webui.bat` file and remove the --deepspeed flag there and check again?

**Comment by Boof2015** [comment]
Seems to work fine without the `--deepspeed` flag
