### ISSUE TITLE
can't run the webui

### ISSUE THREAD

**Issue by paul-ferragut** [daswer123/xtts-webui#37]
Installation went without error but when I try to run the webui:

Traceback (most recent call last):
  File "C:\Users\Paul\Documents\Coding\xtts\xtts-webui\app.py", line 67, in <module>
    from xtts_webui import demo
  File "C:\Users\Paul\Documents\Coding\xtts\xtts-webui\xtts_webui.py", line 3, in <module>
    from scripts.tts_funcs import TTSWrapper
  File "C:\Users\Paul\Documents\Coding\xtts\xtts-webui\scripts\tts_funcs.py", line 3, in <module>
    import torch
  File "C:\Users\Paul\Documents\Coding\xtts\xtts-webui\venv\Lib\site-packages\torch\__init__.py", line 139, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\Paul\Documents\Coding\xtts\xtts-webui\venv\Lib\site-packages\torch\lib\torch_python.dll" or one of its dependencies

**Comment by kevinpawsey** [comment]
there is an issue with transformers at the moment:
https://github.com/huggingface/transformers/issues/28649
the solution I have found is NOT to install 4.37.0
`pip install transformers==4.36.2`
