### ISSUE TITLE
When using the fine-tuning web-ui, I get an error when trying to process WAVs

### ISSUE THREAD

**Issue by Chris2918** [daswer123/xtts-webui#4]
Hello! I am trying to fine-tune xTTS-v2 on about 300 english clips, and I chose the small Whisper model , when I clicked on the "Create dataset" button, I get this error

Traceback (most recent call last):██████████████████████████████████████████████████| 484M/484M [00:58<00:00, 7.64MB/s]
  File "C:\Users\lccji\Downloads\xtts-webui-main\xtts_finetune_webui.py", line 252, in preprocess_dataset
    train_meta, eval_meta, audio_total_size = format_audio_list(audio_path, whisper_model = whisper_model, target_language=language, out_path=out_path, gradio_progress=progress)
  File "C:\Users\lccji\Downloads\xtts-webui-main\scripts\utils\formatter.py", line 111, in format_audio_list
    segments = list(segments)
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\faster_whisper\transcribe.py", line 941, in restore_speech_timestamps
    for segment in segments:
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\faster_whisper\transcribe.py", line 445, in generate_segments
    encoder_output = self.encode(segment)
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\faster_whisper\transcribe.py", line 629, in encode
    return self.model.encode(features, to_cpu=to_cpu)
RuntimeError: Library cublas64_11.dll is not found or cannot be loaded

**Comment by daswer123** [comment]
Hi thanks for letting me know, I have already updated and fixed the issue.

**Comment by Chris2918** [comment]
Thank you! It works now, and I was able to fine-tune the model and optimize it. However, when trying to inference, and load the fine-tuned model, I get this error:
Traceback (most recent call last):
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\gradio\queueing.py", line 459, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\gradio\blocks.py", line 1533, in process_api
    result = await self.call_function(
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\gradio\blocks.py", line 1151, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\gradio\utils.py", line 678, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\lccji\Downloads\xtts-webui-main\xtts_finetune_webui.py", line 51, in load_model
    XTTS_MODEL.load_checkpoint(config, checkpoint_path=xtts_checkpoint, vocab_path=xtts_vocab, use_deepspeed=False)
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\TTS\tts\models\xtts.py", line 759, in load_checkpoint
    speaker_file_path = speaker_file_path or os.path.join(checkpoint_dir, "speakers_xtts.pth")
  File "C:\Users\lccji\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 104, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\gradio\queueing.py", line 459, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\gradio\blocks.py", line 1533, in process_api
    result = await self.call_function(
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\gradio\blocks.py", line 1151, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\gradio\utils.py", line 678, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\lccji\Downloads\xtts-webui-main\xtts_finetune_webui.py", line 51, in load_model
    XTTS_MODEL.load_checkpoint(config, checkpoint_path=xtts_checkpoint, vocab_path=xtts_vocab, use_deepspeed=False)
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\TTS\tts\models\xtts.py", line 759, in load_checkpoint
    speaker_file_path = speaker_file_path or os.path.join(checkpoint_dir, "speakers_xtts.pth")
  File "C:\Users\lccji\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 104, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\gradio\queueing.py", line 497, in process_events
    response = await self.call_prediction(awake_events, batch)
  File "C:\Users\lccji\Downloads\xtts-webui-main\venv\lib\site-packages\gradio\queueing.py", line 468, in call_prediction
    raise Exception(str(error) if show_error else None) from error
Exception: None

**Comment by daswer123** [comment]
It's because of the new tts 0.22.0

I fixed it and also made it so that all important files will be moved to the ready folder inside the specified directory. You will be able to copy this folder to the models folder and use this model in the main interface
