### ISSUE TITLE
RVC not working 

### ISSUE THREAD

**Issue by MrsHorrid** [daswer123/xtts-webui#48]
i keep getting this weird error despite having my mlodel in a folder in the v2v rvc folder

Traceback (most recent call last):
  File "C:\aistuffsies\xttsgui\xtts-webui\venv\Lib\site-packages\gradio\queueing.py", line 489, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\aistuffsies\xttsgui\xtts-webui\venv\Lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\aistuffsies\xttsgui\xtts-webui\venv\Lib\site-packages\gradio\blocks.py", line 1570, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\aistuffsies\xttsgui\xtts-webui\venv\Lib\site-packages\gradio\blocks.py", line 1456, in postprocess_data
    outputs_cached = processing_utils.move_files_to_cache(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\aistuffsies\xttsgui\xtts-webui\venv\Lib\site-packages\gradio\processing_utils.py", line 265, in move_files_to_cache
    return client_utils.traverse(data, _move_to_cache, client_utils.is_file_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\aistuffsies\xttsgui\xtts-webui\venv\Lib\site-packages\gradio_client\utils.py", line 923, in traverse
    new_obj[key] = traverse(value, func, is_root)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\aistuffsies\xttsgui\xtts-webui\venv\Lib\site-packages\gradio_client\utils.py", line 919, in traverse
    return func(json_obj)
           ^^^^^^^^^^^^^^
  File "C:\aistuffsies\xttsgui\xtts-webui\venv\Lib\site-packages\gradio\processing_utils.py", line 257, in _move_to_cache
    temp_file_path = move_resource_to_block_cache(payload.path, block)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\aistuffsies\xttsgui\xtts-webui\venv\Lib\site-packages\gradio\processing_utils.py", line 234, in move_resource_to_block_cache
    return block.move_resource_to_block_cache(url_or_file_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\aistuffsies\xttsgui\xtts-webui\venv\Lib\site-packages\gradio\blocks.py", line 258, in move_resource_to_block_cache
    temp_file_path = processing_utils.save_file_to_cache(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\aistuffsies\xttsgui\xtts-webui\venv\Lib\site-packages\gradio\processing_utils.py", line 170, in save_file_to_cache
    temp_dir = hash_file(file_path)
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\aistuffsies\xttsgui\xtts-webui\venv\Lib\site-packages\gradio\processing_utils.py", line 102, in hash_file
    with open(file_path, "rb") as f:
         ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\aistuffsies\\xttsgui\\xtts-webui\\output\\rvc_mitest_20240213_183208.wav'

**Comment by MrsHorrid** [comment]
i reinstalled everything on a 3,10 env and now i get this error ...


: 31, 'attn_type': '', 'pos_enc_type': 'abs', 'fp16': False}
2024-02-13 20:53:55 | INFO | rvc_python.modules.vc.pipeline | Loading rmvpe model - base_models/rmvpe.pth
C:\aistuffsies\try\xtts-webui\venv\rvc_venv\lib\site-packages\rvc_python\modules\vc\pipeline.py:240: RuntimeWarning: invalid value encountered in divide
  weight /= weight.sum(axis=1, keepdims=True)
2024-02-13 20:53:57 | WARNING | rvc_python.modules.vc.modules | Traceback (most recent call last):
  File "C:\aistuffsies\try\xtts-webui\venv\rvc_venv\lib\site-packages\rvc_python\modules\vc\modules.py", line 184, in vc_single
    audio_opt = self.pipeline.pipeline(
  File "C:\aistuffsies\try\xtts-webui\venv\rvc_venv\lib\site-packages\rvc_python\modules\vc\pipeline.py", line 415, in pipeline
    self.vc(
  File "C:\aistuffsies\try\xtts-webui\venv\rvc_venv\lib\site-packages\rvc_python\modules\vc\pipeline.py", line 241, in vc
    npy = np.sum(big_npy[ix] * np.expand_dims(weight, axis=2), axis=1)
IndexError: index -1 is out of bounds for axis 0 with size 0

Traceback (most recent call last):
  File "C:\Users\shell\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\shell\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\aistuffsies\try\xtts-webui\venv\rvc_venv\lib\site-packages\rvc_python\__main__.py", line 31, in <module>
    inferred_path = infer_file(
  File "C:\aistuffsies\try\xtts-webui\venv\rvc_venv\lib\site-packages\rvc_python\infer.py", line 49, in infer_file
    wavfile.write(opt_path, vc.tgt_sr, wav_opt)
  File "C:\aistuffsies\try\xtts-webui\venv\rvc_venv\lib\site-packages\scipy\io\wavfile.py", line 771, in write
    dkind = data.dtype.kind
AttributeError: 'tuple' object has no attribute 'dtype'

**Comment by Someonetoldme584** [comment]
I cant event load RVC :D how did you make it ? where did you put the model i put in rvc but didnt worked

**Comment by daswer123** [comment]
Guys now busy with work projects, no time to help you, as soon as I finish I will try to help you

**Comment by kalikin** [comment]
I have a problem with RVC on Python 3.11. Running with 3.10 it goes away for me. Hope this helps.

**Comment by Oninaig** [comment]
Did you find a solution for this? Python 3.10 doesn't work either.

**Comment by waruigi** [comment]
Since I'm using Python 3.10.6 and generating text2voice gives me a different error, figure I'd weigh in too. Cmd Log:

```
2024-03-11 23:44:07.284 | INFO     | scripts.tts_funcs:local_generation:355 - Processing time: 1.56 seconds.
2024-03-11 23:44:16 | INFO | fairseq.tasks.text_to_speech | Please install tensorboardX: pip install tensorboardX
File rmvpe.pt not found, start loading...
Traceback (most recent call last):
  File "C:\xtts-webui\venv\rvc_venv\lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "C:\xtts-webui\venv\rvc_venv\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "C:\xtts-webui\venv\rvc_venv\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "C:\xtts-webui\venv\rvc_venv\lib\site-packages\urllib3\connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "C:\xtts-webui\venv\rvc_venv\lib\site-packages\urllib3\connection.py", line 653, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "C:\xtts-webui\venv\rvc_venv\lib\site-packages\urllib3\connection.py", line 806, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "C:\xtts-webui\venv\rvc_venv\lib\site-packages\urllib3\util\ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "C:\xtts-webui\venv\rvc_venv\lib\site-packages\urllib3\util\ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\xtts-webui\venv\rvc_venv\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "C:\xtts-webui\venv\rvc_venv\lib\site-packages\urllib3\connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "C:\xtts-webui\venv\rvc_venv\lib\site-packages\urllib3\util\retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "C:\xtts-webui\venv\rvc_venv\lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "C:\xtts-webui\venv\rvc_venv\lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "C:\xtts-webui\venv\rvc_venv\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "C:\xtts-webui\venv\rvc_venv\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "C:\xtts-webui\venv\rvc_venv\lib\site-packages\urllib3\connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "C:\xtts-webui\venv\rvc_venv\lib\site-packages\urllib3\connection.py", line 653, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "C:\xtts-webui\venv\rvc_venv\lib\site-packages\urllib3\connection.py", line 806, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "C:\xtts-webui\venv\rvc_venv\lib\site-packages\urllib3\util\ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "C:\xtts-webui\venv\rvc_venv\lib\site-packages\urllib3\util\ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\xtts-webui\venv\rvc_venv\lib\site-packages\rvc_python\__main__.py", line 31, in <module>
    inferred_path = infer_file(
  File "C:\xtts-webui\venv\rvc_venv\lib\site-packages\rvc_python\infer.py", line 30, in infer_file
    download_rvc_models(lib_dir)
  File "C:\xtts-webui\venv\rvc_venv\lib\site-packages\rvc_python\download_model.py", line 27, in download_rvc_models
    response = requests.get(url)
  File "C:\xtts-webui\venv\rvc_venv\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\xtts-webui\venv\rvc_venv\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\xtts-webui\venv\rvc_venv\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\xtts-webui\venv\rvc_venv\lib\site-packages\requests\sessions.py", line 725, in send
    history = [resp for resp in gen]
  File "C:\xtts-webui\venv\rvc_venv\lib\site-packages\requests\sessions.py", line 725, in <listcomp>
    history = [resp for resp in gen]
  File "C:\xtts-webui\venv\rvc_venv\lib\site-packages\requests\sessions.py", line 266, in resolve_redirects
    resp = self.send(
  File "C:\xtts-webui\venv\rvc_venv\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\xtts-webui\venv\rvc_venv\lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Traceback (most recent call last):
  File "C:\xtts-webui\venv\lib\site-packages\gradio\queueing.py", line 489, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\xtts-webui\venv\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\xtts-webui\venv\lib\site-packages\gradio\blocks.py", line 1570, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\xtts-webui\venv\lib\site-packages\gradio\blocks.py", line 1456, in postprocess_data
    outputs_cached = processing_utils.move_files_to_cache(
  File "C:\xtts-webui\venv\lib\site-packages\gradio\processing_utils.py", line 265, in move_files_to_cache
    return client_utils.traverse(data, _move_to_cache, client_utils.is_file_obj)
  File "C:\xtts-webui\venv\lib\site-packages\gradio_client\utils.py", line 919, in traverse
    return func(json_obj)
  File "C:\xtts-webui\venv\lib\site-packages\gradio\processing_utils.py", line 257, in _move_to_cache
    temp_file_path = move_resource_to_block_cache(payload.path, block)
  File "C:\xtts-webui\venv\lib\site-packages\gradio\processing_utils.py", line 234, in move_resource_to_block_cache
    return block.move_resource_to_block_cache(url_or_file_path)
  File "C:\xtts-webui\venv\lib\site-packages\gradio\blocks.py", line 258, in move_resource_to_block_cache
    temp_file_path = processing_utils.save_file_to_cache(
  File "C:\xtts-webui\venv\lib\site-packages\gradio\processing_utils.py", line 170, in save_file_to_cache
    temp_dir = hash_file(file_path)
  File "C:\xtts-webui\venv\lib\site-packages\gradio\processing_utils.py", line 102, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\xtts-webui\\output\\reference_PatrickWarburton_12.wav'
```

**Comment by Jack74r** [comment]
Did you fix the RVC problem ? 
For me when i select my RVC pth file and Run, no error but my CPU is 100% and my graphic card 0 , i stopped after 1 hour

**Comment by GamingDaveUk** [comment]
Its been sat doing something but not doing anything for about 10 minutes here... i am sure its errored as rvc is usually fast

**Comment by Daedalus-1337** [comment]
I have the same issue. it sits there with this 2024-05-13 11:09:40 | INFO | rvc_python.modules.vc.pipeline | Loading rmvpe model - base_models/rmvpe.pth 
like its trying to load the basemodel but its failing to do so, it just pins the cpu at 100% and does nothing.
i tried the other modes like crepe and harvest but it does the same thing . i tried giving it the rmvpe.pth model and put it in xtts-webui\models but it didnt make a difference. https://github.com/Vali-98/XTTS-RVC-UI this works fine and its basicly doing the same thing but it doesn't have the same controll over the intial tts generation so I would like to get this xtts-webui to work with rvc

**Comment by deeplearner5** [comment]
> I have the same issue. it sits there with this 2024-05-13 11:09:40 | INFO | rvc_python.modules.vc.pipeline | Loading rmvpe model - base_models/rmvpe.pth like its trying to load the basemodel but its failing to do so, it just pins the cpu at 100% and does nothing. i tried the other modes like crepe and harvest but it does the same thing . i tried giving it the rmvpe.pth model and put it in xtts-webui\models but it didnt make a difference. https://github.com/Vali-98/XTTS-RVC-UI this works fine and its basicly doing the same thing but it doesn't have the same controll over the intial tts generation so I would like to get this xtts-webui to work with rvc

+1 on this - came here wondering if it was an issue at my end, I'm clearly not alone.

**Comment by Appass** [comment]
Same issue for me running on python 3.10.9, v2.0.2 on xtts.

**Comment by PrometheusDante** [comment]
Same for me. It doesn't throw an error, but just computes endlessly until manually stopped.

**Comment by Vektor369** [comment]
Did anyone ever figure this out? This seems like it should be a pretty simple fix...

**Comment by JuSacco** [comment]
If you are stucking at: 
`2024-05-13 11:09:40 | INFO | rvc_python.modules.vc.pipeline | Loading rmvpe model - base_models/rmvpe.pt`
Please note readme.txt on root repo dir:
> WARNING: for some reason some people have RVC hangs, the reason is that you are using the index file, try deleting it and restart the interface
>
>Speaker models you can put in webui/speakers folder or add them through the interface

That works for me

**Comment by Daedalus-1337** [comment]
> If you are stucking at: `2024-05-13 11:09:40 | INFO | rvc_python.modules.vc.pipeline | Loading rmvpe model - base_models/rmvpe.pt` Please note readme.txt on root repo dir:
> 
> > WARNING: for some reason some people have RVC hangs, the reason is that you are using the index file, try deleting it and restart the interface
> > Speaker models you can put in webui/speakers folder or add them through the interface
> 
> That works for me

This worked for me thanks
