### ISSUE TITLE
Failed to load PyTorch C extensions

### ISSUE THREAD

**Issue by BigbUg001** [daswer123/xtts-webui#53]
I am getting this error when i start "start_xtts_webui.bat":

Traceback (most recent call last):
  File "C:\Users\jadso\xtts-webui\app.py", line 67, in <module>
    from xtts_webui import demo
  File "C:\Users\jadso\xtts-webui\xtts_webui.py", line 3, in <module>
    from scripts.tts_funcs import TTSWrapper
  File "C:\Users\jadso\xtts-webui\scripts\tts_funcs.py", line 3, in <module>
    import torch
  File "C:\Users\jadso\xtts-webui\venv\lib\site-packages\torch\__init__.py", line 451, in <module>
    raise ImportError(textwrap.dedent('''
ImportError: Failed to load PyTorch C extensions:
    It appears that PyTorch has loaded the `torch/_C` folder
    of the PyTorch repository rather than the C extensions which
    are expected in the `torch._C` namespace. This can occur when
    using the `install` workflow. e.g.
        $ python setup.py install && python -c "import torch"

    This error can generally be solved using the `develop` workflow
        $ python setup.py develop && python -c "import torch"  # This should succeed
    or by running Python from a different directory.

i tried to reinstall PyTorch, Cuda, everything, but didnt work.
What am i doing wrong?

**Comment by H1nkik** [comment]
I have the same question.

ImportError: Failed to load PyTorch C extensions:
    It appears that PyTorch has loaded the `torch/_C` folder
    of the PyTorch repository rather than the C extensions which
    are expected in the `torch._C` namespace. This can occur when
    using the `install` workflow. e.g.
        $ python setup.py install && python -c "import torch"

    This error can generally be solved using the `develop` workflow
        $ python setup.py develop && python -c "import torch"  # This should succeed
    or by running Python from a different directory.

**Comment by jesanli** [comment]
> I have the same question.
> 
> ImportError: Failed to load PyTorch C extensions: It appears that PyTorch has loaded the `torch/_C` folder of the PyTorch repository rather than the C extensions which are expected in the `torch._C` namespace. This can occur when using the `install` workflow. e.g. $ python setup.py install && python -c "import torch"
> 
> ```
> This error can generally be solved using the `develop` workflow
>     $ python setup.py develop && python -c "import torch"  # This should succeed
> or by running Python from a different directory.
> ```

do you have  solve this question? i meet it  and want you help
