### ISSUE TITLE
Fine-tuning Error - FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by wylken** [daswer123/xtts-webui#58]
I'm trying to execute the fine-tuning, however, I'm receiving the following error:

`Train csv and eval csv already exists
finetuned_models\finetune_primo
>> DVAE weights restored from: C:\Users\wylken\Documents\Projetos\xtts-webui\models\v2.0.2\dvae.pth
Traceback (most recent call last):
  File "C:\Users\wylken\Documents\Projetos\xtts-webui\modules\train.py", line 87, in train_model
    speaker_xtts_path, config_path, original_xtts_checkpoint, vocab_file, exp_path, speaker_wav = train_gpt(
                                                                                                  ^^^^^^^^^^
  File "C:\Users\wylken\Documents\Projetos\xtts-webui\scripts\utils\gpt_train.py", line 175, in train_gpt
    train_samples, eval_samples = load_tts_samples(
                                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\wylken\Documents\Projetos\xtts-webui\venv\Lib\site-packages\TTS\tts\datasets\__init__.py", line 120, in load_tts_samples
    meta_data_train = formatter(root_path, meta_file_train, ignored_speakers=ignored_speakers)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wylken\Documents\Projetos\xtts-webui\venv\Lib\site-packages\TTS\tts\datasets\formatters.py", line 59, in coqui
    with open(filepath, "r", encoding="utf8") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'finetuned_models\\finetune_primo\\dataset\\metadata_train.csv'`

**Comment by IVIaV** [comment]
So if you try to do this via the Fine-Tune tab, it's no wonder why it doesn't work. ;)
You have to download an extra UI for fine-tuning (at least that's how I did it and understood it):

https://github.com/daswer123/xtts-finetune-webui
