### ISSUE TITLE
cant train not on collab and not locally anymore 

### ISSUE THREAD

**Issue by MrsHorrid** [daswer123/xtts-webui#64]
97% 205M/211M [00:03<00:00, 67.3MiB/s]
100% 211M/211M [00:18<00:00, 67.3MiB/s]>> DVAE weights restored from: /content/xtts-webui/models/v2.0.2/dvae.pth
 | > Found 58 files in /content/xtts-webui/finetuned_models/ShakedAudio/dataset
usage: app.py [-h] [--continue_path CONTINUE_PATH] [--restore_path RESTORE_PATH]
              [--best_path BEST_PATH] [--use_ddp true/false] [--use_accelerate true/false]
              [--grad_accum_steps GRAD_ACCUM_STEPS] [--overfit_batch true/false]
              [--skip_train_epoch true/false] [--start_with_eval true/false]
              [--small_run SMALL_RUN] [--gpu GPU] [--rank RANK] [--group_id GROUP_ID]
app.py: error: argument -h/--help: ignored explicit argument 's'
Traceback (most recent call last):
  File "/usr/lib/python3.10/argparse.py", line 1878, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.10/argparse.py", line 2091, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python3.10/argparse.py", line 1999, in consume_optional
    raise ArgumentError(action, msg % explicit_arg)
argparse.ArgumentError: argument -h/--help: ignored explicit argument 's'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/xtts-webui/modules/train.py", line 87, in train_model
    speaker_xtts_path, config_path, original_xtts_checkpoint, vocab_file, exp_path, speaker_wav = train_gpt(
  File "/content/xtts-webui/scripts/utils/gpt_train.py", line 183, in train_gpt
    trainer = Trainer(
  File "/usr/local/lib/python3.10/dist-packages/trainer/trainer.py", line 397, in __init__
    args, coqpit_overrides = self.parse_argv(args)
  File "/usr/local/lib/python3.10/dist-packages/trainer/trainer.py", line 680, in parse_argv
    training_args, coqpit_overrides = parser.parse_known_args()
  File "/usr/lib/python3.10/argparse.py", line 1881, in parse_known_args
    self.error(str(err))
  File "/usr/lib/python3.10/argparse.py", line 2606, in error
    self.exit(2, _('%(prog)s: error: %(message)s\n') % args)
  File "/usr/lib/python3.10/argparse.py", line 2593, in exit
    _sys.exit(status)
SystemExit: 2
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 489, in call_prediction
    output = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1561, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1179, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 678, in wrapper
    response = f(*args, **kwargs)
  File "/content/xtts-webui/modules/train.py", line 245, in train_xtts_model
    shutil.copy(speaker_reference_path, reference_destination)
  File "/usr/lib/python3.10/shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'finetuned_models/ShakedAudio/ready/reference.wav'

**Comment by VitaliyAT** [comment]
the same 
```
 File "C:\Users\1\AppData\Local\Programs\Python\Python31011\lib\shutil.py", line 557, in copytree
    with os.scandir(src) as itr:
FileNotFoundError: [WinError 3] Системе не удается найти указанный путь: 
```
I am crying
