### ISSUE TITLE
Error when using finetune to create a dataset.

### ISSUE THREAD

**Issue by Atoli** [daswer123/xtts-webui#7]
OS: Windows 10 LTSC.
GPU: Nvidia RTX 3060 (12GB).

When i try to create a dataset with `start_xtts_finetune_webui.bat` i get the following error:

```
Existing language matches target language
Loading Whisper Model!
Traceback (most recent call last):
  File "C:\Users\PC\Desktop\xtts-webui\xtts_finetune_webui.py", line 246, in preprocess_dataset
    train_meta, eval_meta, audio_total_size = format_audio_list(audio_path, whisper_model = whisper_model, target_language=language, out_path=out_path, gradio_progress=progress)
  File "C:\Users\PC\Desktop\xtts-webui\scripts\utils\formatter.py", line 77, in format_audio_list
    asr_model = WhisperModel(whisper_model, device=device, compute_type="float16")
  File "C:\Users\PC\Desktop\xtts-webui\venv\lib\site-packages\faster_whisper\transcribe.py", line 130, in __init__
    self.model = ctranslate2.models.Whisper(
ValueError: Requested float16 compute type, but the target device or backend do not support efficient float16 computation.
```

What could the problem be? Does my GPU not meet the criteria or something? That makes no sense, the RTX 3060 **DOES** support float16.
I can clone voices and do inferences, but if i try a finetune i get this error.

**Comment by daswer123** [comment]
Maybe torch was not installed correctly during installation and the cpu version was installed. Try reinstalling the dependencies and try again

**Comment by Atoli** [comment]
> Maybe torch was not installed correctly during installation and the cpu version was installed. Try reinstalling the dependencies and try again

How do i check if i installed the cpu version?

I used the following syntax:

`pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118`

From here:

https://pytorch.org/get-started/locally/

**Comment by daswer123** [comment]
Try this, 
1) call the console in the project folder
2) enter the command `venv/scripts/activate` or `source venv/scripts/activate` if you use linux.
3) type `pip show torch` and see what version of torch you have.
4) If there is no `+cu118` prefix there, type `pip install torch==2.1.1+cu118 torchaudio==2.1.1+cu118 --index-url https://download.pytorch.org/whl/cu118`.

**Comment by Atoli** [comment]
> Try this,
> 
> 1. call the console in the project folder
> 2. enter the command `venv/scripts/activate` or `source venv/scripts/activate` if you use linux.
> 3. type `pip show torch` and see what version of torch you have.
> 4. If there is no `+cu118` prefix there, type `pip install torch==2.1.1+cu118 torchaudio==2.1.1+cu118 --index-url https://download.pytorch.org/whl/cu118`.

Thank you! It seemed it was not there and i was able to process data.
I processed an audio file (that met the criteria) and some files were generated, then i went to the the finetune encoder tab and loaded the cvs files.

When i press run i get the following error:

```
Traceback (most recent call last):
  File "C:\Users\PC\Desktop\xtts-webui\xtts_finetune_webui.py", line 358, in train_model
    speaker_xtts_path,config_path, original_xtts_checkpoint, vocab_file, exp_path, speaker_wav = train_gpt(custom_model,version,language, num_epochs, batch_size, grad_acumm, train_csv, eval_csv, output_path=output_path, max_audio_length=max_audio_length)
  File "C:\Users\PC\Desktop\xtts-webui\scripts\utils\gpt_train.py", line 97, in train_gpt
    shutil.copy(XTTS_SPEAKER_FILE, NEW_XTTS_SPEAKER_FILE)
  File "C:\Python310\lib\shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Python310\lib\shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\PC\\Desktop\\xtts-webui\\models\\v2.0.2\\speakers_xtts.pth'
Traceback (most recent call last):
  File "C:\Users\PC\Desktop\xtts-webui\venv\lib\site-packages\gradio\queueing.py", line 459, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\Users\PC\Desktop\xtts-webui\venv\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\PC\Desktop\xtts-webui\venv\lib\site-packages\gradio\blocks.py", line 1542, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\PC\Desktop\xtts-webui\venv\lib\site-packages\gradio\blocks.py", line 1369, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "C:\Users\PC\Desktop\xtts-webui\venv\lib\site-packages\gradio\blocks.py", line 1343, in validate_outputs
    raise ValueError(
ValueError: An event handler (train_model) didn't receive enough output values (needed: 6, received: 5).
Wanted outputs:
    [label, textbox, textbox, textbox, textbox, textbox]
Received outputs:
    ["The training was interrupted due an error !! Please check the console to check the full error message!
 Error summary: Traceback (most recent call last):
  File "C:\Users\PC\Desktop\xtts-webui\xtts_finetune_webui.py", line 358, in train_model
    speaker_xtts_path,config_path, original_xtts_checkpoint, vocab_file, exp_path, speaker_wav = train_gpt(custom_model,version,language, num_epochs, batch_size, grad_acumm, train_csv, eval_csv, output_path=output_path, max_audio_length=max_audio_length)
  File "C:\Users\PC\Desktop\xtts-webui\scripts\utils\gpt_train.py", line 97, in train_gpt
    shutil.copy(XTTS_SPEAKER_FILE, NEW_XTTS_SPEAKER_FILE)
  File "C:\Python310\lib\shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Python310\lib\shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\PC\\Desktop\\xtts-webui\\models\\v2.0.2\\speakers_xtts.pth'
", "", "", "", ""]
Traceback (most recent call last):
  File "C:\Users\PC\Desktop\xtts-webui\venv\lib\site-packages\gradio\queueing.py", line 459, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\Users\PC\Desktop\xtts-webui\venv\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\PC\Desktop\xtts-webui\venv\lib\site-packages\gradio\blocks.py", line 1542, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\PC\Desktop\xtts-webui\venv\lib\site-packages\gradio\blocks.py", line 1369, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "C:\Users\PC\Desktop\xtts-webui\venv\lib\site-packages\gradio\blocks.py", line 1343, in validate_outputs
    raise ValueError(
ValueError: An event handler (train_model) didn't receive enough output values (needed: 6, received: 5).
Wanted outputs:
    [label, textbox, textbox, textbox, textbox, textbox]
Received outputs:
    ["The training was interrupted due an error !! Please check the console to check the full error message!
 Error summary: Traceback (most recent call last):
  File "C:\Users\PC\Desktop\xtts-webui\xtts_finetune_webui.py", line 358, in train_model
    speaker_xtts_path,config_path, original_xtts_checkpoint, vocab_file, exp_path, speaker_wav = train_gpt(custom_model,version,language, num_epochs, batch_size, grad_acumm, train_csv, eval_csv, output_path=output_path, max_audio_length=max_audio_length)
  File "C:\Users\PC\Desktop\xtts-webui\scripts\utils\gpt_train.py", line 97, in train_gpt
    shutil.copy(XTTS_SPEAKER_FILE, NEW_XTTS_SPEAKER_FILE)
  File "C:\Python310\lib\shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Python310\lib\shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\PC\\Desktop\\xtts-webui\\models\\v2.0.2\\speakers_xtts.pth'
", "", "", "", ""]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\PC\Desktop\xtts-webui\venv\lib\site-packages\gradio\queueing.py", line 497, in process_events
    response = await self.call_prediction(awake_events, batch)
  File "C:\Users\PC\Desktop\xtts-webui\venv\lib\site-packages\gradio\queueing.py", line 468, in call_prediction
    raise Exception(str(error) if show_error else None) from error
Exception: None
```

Tried with different datasets, it seems there are some .py filed missing or something?

**Comment by daswer123** [comment]
Try deleting the v2.0.2 folder in the models folder and start the training again
