### ISSUE TITLE
Cant run xtts webui

### ISSUE THREAD

**Issue by MaximusStalsky** [daswer123/xtts-webui#70]
Traceback (most recent call last):
  File "G:\TTS\xtts-webui-main\app.py", line 1, in <module>
    from scripts.modeldownloader import install_deepspeed_based_on_python_version
  File "G:\TTS\xtts-webui-main\scripts\modeldownloader.py", line 4, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

also during pip install requests i get this

DEPRECATION: omegaconf 2.0.6 has a non-standard dependency specifier PyYAML>=5.1.*. pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of omegaconf or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063

**Comment by raivohdus** [comment]
Just upgrading pip helped for me

**Comment by SeBL4RD** [comment]
Personnally, i have same error on starting start_xtts_webui.bat, during install.bat, i have this error about jamo : 

```
Collecting jamo
  Using cached jamo-0.4.0.tar.gz (7.3 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Seb\AppData\Local\Temp\pip-install-aiwh06nm\jamo_f65e883f9bd04095958a78c655cbe77c\setup.py", line 11, in <module>
          long_description = f.read()
        File "C:\Users\Seb\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 707: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

[notice] A new release of pip available: 22.3.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip
Looking in indexes: https://download.pytorch.org/whl/cu118
Requirement already satisfied: torch==2.1.1+cu118 in f:\ia\audio\xtts-webui\venv\lib\site-packages (2.1.1+cu118)
Requirement already satisfied: torchaudio==2.1.1+cu118 in f:\ia\audio\xtts-webui\venv\lib\site-packages (2.1.1+cu118)
Requirement already satisfied: sympy in f:\ia\audio\xtts-webui\venv\lib\site-packages (from torch==2.1.1+cu118) (1.12)
Requirement already satisfied: fsspec in f:\ia\audio\xtts-webui\venv\lib\site-packages (from torch==2.1.1+cu118) (2024.2.0)
Requirement already satisfied: jinja2 in f:\ia\audio\xtts-webui\venv\lib\site-packages (from torch==2.1.1+cu118) (3.1.3)
Requirement already satisfied: typing-extensions in f:\ia\audio\xtts-webui\venv\lib\site-packages (from torch==2.1.1+cu118) (4.9.0)
Requirement already satisfied: networkx in f:\ia\audio\xtts-webui\venv\lib\site-packages (from torch==2.1.1+cu118) (3.2.1)
Requirement already satisfied: filelock in f:\ia\audio\xtts-webui\venv\lib\site-packages (from torch==2.1.1+cu118) (3.13.1)
Requirement already satisfied: MarkupSafe>=2.0 in f:\ia\audio\xtts-webui\venv\lib\site-packages (from jinja2->torch==2.1.1+cu118) (2.1.5)
Requirement already satisfied: mpmath>=0.19 in f:\ia\audio\xtts-webui\venv\lib\site-packages (from sympy->torch==2.1.1+cu118) (1.3.0)

[notice] A new release of pip available: 22.3.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip
Install deepspeed for windows for python 3.10.x and CUDA 11.8
Traceback (most recent call last):
  File "F:\IA\AUDIO\xtts-webui\scripts\modeldownloader.py", line 4, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Install complete.
Appuyez sur une touche pour continuer...
```

**Comment by SeBL4RD** [comment]
I manually put jamo 0.4.0 in site-packages, looks working for me :)

**Comment by Vektor369** [comment]
> I manually put jamo 0.4.0 in site-packages, looks working for me :)

Where do you get jamo 0.4.0?

**Comment by DukemFIVE** [comment]
> Took me several hours, but here's what got it started for me:
> 
> Start a console from `xtts-webui`.
> 
> ```
> python -m venv venv
> venv\Scripts\activate
> pip install requests
> pip install tqdm
> pip install packaging
> pip install loguru
> ```
> 
> Close console. Run `start_xtts_webui.bat`. Recieve an error. Close console. Start a new console.
> 
> ```
> python -m venv venv
> venv\Scripts\activate
> pip install tts
> ```
> 
> Close console. Run `start_xtts_webui.bat`. Recieve an error. Close console. Start a new console.
> 
> ```
> python -m venv venv
> venv\Scripts\activate
> pip install -r requirements.txt
> ```
> 
> Now, I did get the error:
> 
> ```
> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
> fastapi-cli 0.0.3 requires typer>=0.12.3, but you have typer 0.9.4 which is incompatible.
> ```
> 
> But I exited the console anyway, ran `start_xtts_webui.bat`, and it opened. Not sure _why_ or _how_ any of this worked, because I have absolutely no idea what I'm doing. And I'm sure there's a _much_ easier and less tedious way of doing all of this. All I know is that this is what worked for me.
> 
> Best of luck.

Thanks that worked for me too !!

I had the same problem with installing jamo 0.4.0

**Comment by Vektor369** [comment]
> Thanks that worked for me too !!
> 
> I had the same problem with installing jamo 0.4.0

Wow! I am very happy, but also very surprised. So, I'm basically here right now:

![programming-3a](https://github.com/daswer123/xtts-webui/assets/124237282/76a4f0c3-42e0-4305-b3e2-8bfec0bc85ed)

**Comment by tjw2469** [comment]
> > Took me several hours, but here's what got it started for me:
> > Start a console from `xtts-webui`.
> > ```
> > python -m venv venv
> > venv\Scripts\activate
> > pip install requests
> > pip install tqdm
> > pip install packaging
> > pip install loguru
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Close console. Run `start_xtts_webui.bat`. Recieve an error. Close console. Start a new console.
> > ```
> > python -m venv venv
> > venv\Scripts\activate
> > pip install tts
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Close console. Run `start_xtts_webui.bat`. Recieve an error. Close console. Start a new console.
> > ```
> > python -m venv venv
> > venv\Scripts\activate
> > pip install -r requirements.txt
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Now, I did get the error:
> > ```
> > ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
> > fastapi-cli 0.0.3 requires typer>=0.12.3, but you have typer 0.9.4 which is incompatible.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But I exited the console anyway, ran `start_xtts_webui.bat`, and it opened. Not sure _why_ or _how_ any of this worked, because I have absolutely no idea what I'm doing. And I'm sure there's a _much_ easier and less tedious way of doing all of this. All I know is that this is what worked for me.
> > Best of luck.
> 
> Thanks that worked for me too !!
> 
> I had the same problem with installing jamo 0.4.0

wasn't expect it to work...but it works

**Comment by cyberofficial** [comment]
> But I exited the console anyway, ran `start_xtts_webui.bat`, and it opened. Not sure _why_ or _how_ any of this worked, because I have absolutely no idea what I'm doing. And I'm sure there's a _much_ easier and less tedious way of doing all of this. All I know is that this is what worked for me.
> 
> Best of luck.

![image](https://github.com/daswer123/xtts-webui/assets/19499442/98cac61c-24e3-43c4-bcad-00be066f457e)

**Comment by Arquinz** [comment]
I also had this exact same error. It seems like failure to install jamo causes the entire installation script to cancel the rest of its process. Anyway, i also had another problem which was that activating the virtual enviroment didn't allow me to use pip.exe (Claiming that file cant be found) Anyway, this can be circumvented by simply doing a cmd pip install with --target your\path\here\xtts-webui-main\venv\Lib\site-packages.

Anyway, once you get to the requirements text you can also do that by simply doing: ` pip install -r your\path\here\xtts-webui-main\requirements.txt --target  your\path\here\xtts-webui-main\venv\Lib\site-packages.`

**Comment by Blue84x** [comment]
> Took me several hours, but here's what got it started for me:
> 
> Start a console from `xtts-webui`.
> 
> ```
> python -m venv venv
> venv\Scripts\activate
> pip install requests
> pip install tqdm
> pip install packaging
> pip install loguru
> ```
> 
> Close console. Run `start_xtts_webui.bat`. Recieve an error. Close console. Start a new console.
> 
> ```
> python -m venv venv
> venv\Scripts\activate
> pip install tts
> ```
> 
> Close console. Run `start_xtts_webui.bat`. Recieve an error. Close console. Start a new console.
> 
> ```
> python -m venv venv
> venv\Scripts\activate
> pip install -r requirements.txt
> ```
> 
> Now, I did get the error:
> 
> ```
> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
> fastapi-cli 0.0.3 requires typer>=0.12.3, but you have typer 0.9.4 which is incompatible.
> ```
> 
> But I exited the console anyway, ran `start_xtts_webui.bat`, and it opened. Not sure _why_ or _how_ any of this worked, because I have absolutely no idea what I'm doing. And I'm sure there's a _much_ easier and less tedious way of doing all of this. All I know is that this is what worked for me.
> 
> Best of luck.

Absolute legend. I signed up for an account just to say thank you! It worked. No idea what I did there but it worked.
