### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by Guilded-Aurora** [daswer123/xtts-webui#71]
Traceback (most recent call last):
  File "#Redacted#\xtts-webui\app.py", line 67, in <module>
    from xtts_webui import demo
  File "#Redacted#\xtts-webui\xtts_webui.py", line 97, in <module>
    import modules
  File "#Redacted#\xtts-webui\modules\__init__.py", line 1, in <module>
    import modules.text2voice
  File "#Redacted#\xtts-webui\modules\text2voice\__init__.py", line 1, in <module>
    import modules.text2voice.generation
  File "#Redacted#\xtts-webui\modules\text2voice\generation.py", line 7, in <module>
    from scripts.funcs import improve_and_convert_audio, resemble_enhance_audio, str_to_list
  File "#Redacted#\xtts-webui\scripts\funcs.py", line 4, in <module>
    from scripts.resemble_enhance.enhancer.inference import denoise, enhance
  File "#Redacted#\xtts-webui\scripts\resemble_enhance\enhancer\inference.py", line 6, in <module>
    from ..inference import inference
  File "#Redacted#\xtts-webui\scripts\resemble_enhance\inference.py", line 12, in <module>
    from .hparams import HParams
  File "#Redacted#\xtts-webui\scripts\resemble_enhance\hparams.py", line 36, in <module>
    class HParams:
  File "#Redacted#\xtts-webui\scripts\resemble_enhance\hparams.py", line 105, in HParams
    def load(cls, run_dir, yaml: Path | None = None):
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

I also had to re-install modules like requests and gradio manually, but after all the reinstalls I got to this.

**Comment by MackNcD** [comment]
Having the same issue, literally a day prior it was working on both 3.10 _and_ 3.11
