### ISSUE TITLE
Hindi Doesn't Work.

### ISSUE THREAD

**Issue by bishtyyy** [daswer123/xtts-webui#75]
When i select hindi from language section and press on generate i get the following error message -
Using ready reference
Using folder reference
None  test
C:\Tools\xtts-webui\temp\resampled_audio_8657cc3a-7662-40ec-b5f9-d0f93f283953.wav Test
Traceback (most recent call last):
  File "C:\Tools\xtts-webui\venv\lib\site-packages\gradio\queueing.py", line 489, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\Tools\xtts-webui\venv\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Tools\xtts-webui\venv\lib\site-packages\gradio\blocks.py", line 1561, in process_api
    result = await self.call_function(
  File "C:\Tools\xtts-webui\venv\lib\site-packages\gradio\blocks.py", line 1179, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Tools\xtts-webui\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Tools\xtts-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "C:\Tools\xtts-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "C:\Tools\xtts-webui\venv\lib\site-packages\gradio\utils.py", line 678, in wrapper
    response = f(*args, **kwargs)
  File "C:\Tools\xtts-webui\modules\text2voice\generation.py", line 592, in generate_audio
    output_file = XTTS.process_tts_to_file(
  File "C:\Tools\xtts-webui\scripts\tts_funcs.py", line 443, in process_tts_to_file
    raise e  # Propagate exceptions for endpoint handling.
  File "C:\Tools\xtts-webui\scripts\tts_funcs.py", line 433, in process_tts_to_file
    self.local_generation(
  File "C:\Tools\xtts-webui\scripts\tts_funcs.py", line 335, in local_generation
    out = self.model.inference(
  File "C:\Tools\xtts-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Tools\xtts-webui\venv\lib\site-packages\TTS\tts\models\xtts.py", line 526, in inference
    text = split_sentence(text, language, self.tokenizer.char_limits[language])
KeyError: 'hi'

I have reinstalled the entire program 3-4 times with all necessarcy files and dependencies and it still gives me same error. All the other languages are working fine only hindi is not working. Please look into this and fix the error.

**Comment by iamjamilkhan** [comment]
Same here I’m facing this issue but no update from developer

**Comment by bishtyyy** [comment]
> Same here I’m facing this issue but no update from developer
  i manually installed using the methods provided in the github.. i managed to bypass this error..but the generated hindi audio is total gibberish... its just random sounds..like umm or ahh ...

**Comment by rajeshjsl** [comment]
> > Same here I’m facing this issue but no update from developer
> > i manually installed using the methods provided in the github.. i managed to bypass this error..but the generated hindi audio is total gibberish... its just random sounds..like umm or ahh ...

Have the same issue.

Gibberish output on models 2.0.2 and 2.0.3.
