### ISSUE TITLE
UnboundLocalError: local variable 'ref_voice_opvoice_path' referenced before assignment

### ISSUE THREAD

**Issue by shivdbz2010** [daswer123/xtts-webui#77]
To create a public link, set `share=True` in `launch()`.
hello world
Traceback (most recent call last):
  File "S:\Ai\Audio-AI\xtts-webui\venv\lib\site-packages\gradio\queueing.py", line 489, in call_prediction
    output = await route_utils.call_process_api(
  File "S:\Ai\Audio-AI\xtts-webui\venv\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "S:\Ai\Audio-AI\xtts-webui\venv\lib\site-packages\gradio\blocks.py", line 1561, in process_api
    result = await self.call_function(
  File "S:\Ai\Audio-AI\xtts-webui\venv\lib\site-packages\gradio\blocks.py", line 1179, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "S:\Ai\Audio-AI\xtts-webui\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "S:\Ai\Audio-AI\xtts-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "S:\Ai\Audio-AI\xtts-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "S:\Ai\Audio-AI\xtts-webui\venv\lib\site-packages\gradio\utils.py", line 678, in wrapper
    response = f(*args, **kwargs)
  File "S:\Ai\Audio-AI\xtts-webui\modules\voice2voice.py", line 404, in infer_openvoice_audio
    filename_openvoice = Path(ref_voice_opvoice_path).stem
UnboundLocalError: local variable 'ref_voice_opvoice_path' referenced before assignment

**Comment by shivshankar11** [comment]
single audio mode has this issue, batch mod work fine
