### ISSUE TITLE
Error in install and running on windows 11 "unsuported python version on windows"

### ISSUE THREAD

**Issue by GamingDaveUk** [daswer123/xtts-webui#9]
Followed the install guide, and i have a fair few python related apps on this machine.

```
Install deepspeed for windows for python 3.10.x and CUDA 11.8
2023-12-20 18:46:01.083 | INFO     | __main__:install_deepspeed_based_on_python_version:38 - Python version: 3.9
2023-12-20 18:46:01.083 | ERROR    | __main__:install_deepspeed_based_on_python_version:55 - Unsupported Python version on Windows.
Install complete.
Press any key to continue . . .

(venv) D:\xtta\xtts-webui>start_xtts_webui.bat
2023-12-20 18:46:54.035 | INFO     | scripts.modeldownloader:install_deepspeed_based_on_python_version:38 - Python version: 3.9
2023-12-20 18:46:54.035 | ERROR    | scripts.modeldownloader:install_deepspeed_based_on_python_version:55 - Unsupported Python version on Windows.
Traceback (most recent call last):
  File "D:\xtta\xtts-webui\app.py", line 33, in <module>
    from xtts_webui import demo
  File "D:\xtta\xtts-webui\xtts_webui.py", line 8, in <module>
    from scripts.funcs import save_audio_to_wav,resample_audio,move_and_rename_file,improve_and_convert_audio,improve_ref_audio,resemble_enchance_audio
  File "D:\xtta\xtts-webui\scripts\funcs.py", line 177, in <module>
    from scripts.resemble_enhance.enhancer.inference import denoise, enhance
  File "D:\xtta\xtts-webui\scripts\resemble_enhance\enhancer\inference.py", line 6, in <module>
    from ..inference import inference
  File "D:\xtta\xtts-webui\scripts\resemble_enhance\inference.py", line 12, in <module>
    from .hparams import HParams
  File "D:\xtta\xtts-webui\scripts\resemble_enhance\hparams.py", line 36, in <module>
    class HParams:
  File "D:\xtta\xtts-webui\scripts\resemble_enhance\hparams.py", line 105, in HParams
    def load(cls, run_dir, yaml: Path | None = None):
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

the top part is the end of the install script, the bottom part is where i ran the start script.

**Comment by daswer123** [comment]
```
Install deepspeed for windows for python 3.10.x and CUDA 11.8
2023-12-20 18:46:01.083 | INFO     | __main__:install_deepspeed_based_on_python_version:38 - Python version: 3.9
2023-12-20 18:46:01.083 | ERROR    | __main__:install_deepspeed_based_on_python_version:55 - Unsupported Python version 
```
This project supports only python 3.10 and 3.11

**Comment by GamingDaveUk** [comment]
> ```
> Install deepspeed for windows for python 3.10.x and CUDA 11.8
> 2023-12-20 18:46:01.083 | INFO     | __main__:install_deepspeed_based_on_python_version:38 - Python version: 3.9
> 2023-12-20 18:46:01.083 | ERROR    | __main__:install_deepspeed_based_on_python_version:55 - Unsupported Python version 
> ```
> 
> This project supports only python 3.10 and 3.11

As I say i followed the install instructions.

**Comment by daswer123** [comment]
Great glad the problem is solved

**Comment by GamingDaveUk** [comment]
> Great glad the problem is solved

Only issue i have now is its using cpu not gpu. That could be related to the fact I am using a laptop right now which has an intel gpu and an nvidia one. However when i used the api by itself i did have to make it use the gpu, so may have a same issue with the webui (which I am assuming can also be used as an api?)

**Comment by daswer123** [comment]
To interface a specific graphics card, you can specify this via the -d flag "cuda:0" or "cuda:1" depending on the order in which the system detects these graphics cards.

Gradio has a built-in api client, but I haven't worked that out, so it's probably not possible yet

**Comment by GamingDaveUk** [comment]
> To interface a specific graphics card, you can specify this via the flag `-d` `cuda:0` or `cuda:1` depending on the order in which the system detects these graphics cards.
> 
> Gradio has a built-in api client, but I haven't worked that out, so it's probably not possible yet

Ah i was planning on using this in place of the server api. Installing it on my laptop at work was a test run during my downtime. currently using the xtts server that gets installed with silly tavern but i dont always use silly tavern itself lol 

If this is used to finetune a voice, can that voice model be used in your api?

**Comment by daswer123** [comment]
Not yet, but I will add such a feature in the near future.

**Comment by daswer123** [comment]
@GamingDaveUk 
Done, now in xtts-api-server you can specify a custom model. To do this you need to create a folder with the name of custom model in the models folder, then at startup specify flag -v "Model name".

Also now you can pass the path to the text files in the `text` field and it is considered
